parameters:
    youtube_api_key: '%env(YOUTUBE_API_KEY)%'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    weather_api_key: '%env(WEATHER_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\Finder\Finder:
        shared: false

    App\Service\YouTubeService:
        arguments:
            $apiKey: '%youtube_api_key%'

    App\Service\GeminiService:
        arguments:
            $apiKey: '%gemini_api_key%'

    App\Service\WeatherService:
        arguments:
            $apiKey: '%weather_api_key%'        